### PR TITLE
find time at which derivative of spline reaches a given value 

### PR DESCRIPTION
**Pull request by LukeLabrie**
### Summary
This pr adds an argument called `target` to the `solve()` method of the `CubicHermiteSpline()`, which allows the user to solve for when the derivative of the component of a spline reaches a given value. Prior behavior, i.e. solving for when the state of the component reaches a given value, is maintained as default. 

### Motivation
I'm using `jitcdde` to model some control strategies, some of which are based on state, where this `solve()` method becomes useful to pinpoint the exact time an event happened. Some other strategies are based on the derivatives of state variables. Therefore to pinpoint the timing of these events requires some extra logic. 

### Approach
To solve for the time at which a given component reaches a given value we solve for the roots of the polynomial:

$at^3 + bt^2 + ct +(d-\text{value})$

Where $a,b,c,d$ can be computed from the anchors. To do the same for the derivative is therefore straightforward, and implemented as finding the roots of the polynomial:

$3at^2 + 2bt + (c-\text{value} \cdot \Delta t)$

where $\Delta t$ is the timestep between the anchors.

### Changes
- Changed the variable names representing the state and derivative at the anchor points for clarity. I found that $a,b,c,d$ are often used in the literature to express the coefficients of the Hermite polynomial, which was then confusing to use them to compute these coefficients 
- Added optional argument `target` to the `solve()` method of the `CubicHermiteSpline` class
- Similarly added optional argument `target` to the `solve_from_anchors()` function, and the necessary logic in this function to interpolate the time at which this derivative is reached. 
- Added a some tests within the `TestSolving` class of the test suite

### CODE REVIEW

**Comment by Wrzlprmft** [comment]
Thank you for your pull request. I made two main changes:

* I changed the option to a boolean and renamed it. _Target_ is already used for something completely different in this module. Also, intuitively I would rather use _target_ for the value that the state or derivative should assume.

* The test for `solve` is based on a symbolic polynomial that has roots at given points by construction. It’s straightforward to integrate that polynomial to provide a challenge for the new functionality. With your test, it could have happened that the derivative never assumed the desired values.

If everything is satisfactory and you have no further feedback on this, I would merge your pull request.

**Comment by LukeLabrie** [comment]
Thanks for reviewing -- makes sense to me. Just a couple of things:

- I'm not able to see your changes to the `solve()` or `solve_from_anchors()` methods. Perhaps you haven't committed them? As the PR stands, I think the test is incompatible with my changes. Happy to make the updates myself, but no need if you've already done the work. 

- Currently `solve()` returns the time and the derivative, which is useful when solving for the state to determine upwards/downwards crossings. Maybe it makes sense to return something else when solving for the derivative? Like the state perhaps?

**Comment by Wrzlprmft** [comment]
> I'm not able to see your changes to the `solve()` or `solve_from_anchors()` methods. Perhaps you haven't committed them? As the PR stands, I think the test is incompatible with my changes. Happy to make the updates myself, but no need if you've already done the work.

I did indeed somehow botch committing one of the files. That should be fixed now.

> Currently `solve()` returns the time and the derivative, which is useful when solving for the state to determine upwards/downwards crossings. Maybe it makes sense to return something else when solving for the derivative? Like the state perhaps?

Returning the derivative is indeed pointless for the new functionality. However, changing the output as well would make the method so different that I would rather have a separate method to avoid confusion and errors. While having a separate method can be done of course, I wouldn’t expect there to be a high need for it as evaluating the state at given times should be sufficiently easy with the current set of methods.

But then again, I didn’t expect that anybody would want to find points where the derivative has a specific value, and yet here we are. So, if you think that this is relevant to your use case or similar, that’s sufficient for me to do it.

**Comment by LukeLabrie** [comment]
Thanks! The updates look good to me. 

On the return value, fair enough. For my use case I don't need to know the state when the derivative is reached, only the time is important so I'm ok with how it is currently.

**Pull request merged**
